name: CI
on:
  pull_request:
    branches: ['main']
jobs:
  lint-and-test:
    name: Lint and test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version:
          - 16.x
          - 18.x
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - name: Install
        run: pnpm install
      - name: lint
        run: pnpm lint
      - name: Run tests
        run: pnpm test
